language: node_js
sudo: false
node_js:
  - '6'
  - '7'
  - '8'
env:
  global:
    - CXX=g++-4.8
    - secure: >-
        OKosGQarvGKv95106qkQgSY+sW6QAokv6KWuZt7psSl7zYohCl7lxl4846hji9ev0is/dIJih0XT6os9b06+5dhPuB3xucrRTCFRmlxm4QyGXzi/hxqDWE0GbP7PsYezlumLVATVaIKiYmqCtUq7Vw8D3oWdXP8irqwqdhk6dg2foyr9RBBxg8TQk8rs17Szw3cyyxfz0PeQBar7kT2149PH3iSo2OKY+ytDQMjS37+BzfeCNUskoqmJdmIj9SQQO5ZqlACET7okOc88Q7AWQE8wZ0rfHH2ME0bhjmH61mIAq3B/H35FooEyI5tbtAWxWpw8Qnqjk8peknmq9vEe2PKIYIR9ipJqeIY8lwwrEa/BgNAiOFCXnM4B9Y6n/MwF3mNSOM4sQLope7IBfLCH2WlqiyuANhpyeGH7LHrmlIIGbodFMpAWRKwD5K3iRmbBuC6dOnQugaVow0P/JtXP18dctMN5O17SIpnQrLM7ht/fF6WRQ3UN9ETqlsUnagb4XxqBi2Fa0DcHNqQt+/Fm6gz8XW1FziJMXtPRwGCqHnQHO5ZCdbvSpMpjL/Kj/fcslKXZaXmFo0aFPMy2MkRwgE1HDpxyL3vSzVkm7jV5ycz/65SEPL+SPh4Fts3bBcsooSuoGkrT+S3qyfGGBRlbPjj7hfpuHNVoAKC4WPGmOW8=
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install --global npm
  - npm install
