// flow-typed signature: 0ad3159e2adf4bd9bea059505f416825
// flow-typed version: <<STUB>>/dependency-diff_v^1.0.4/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dependency-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dependency-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dependency-diff/tests/diff/diff' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dependency-diff/index' {
  declare module.exports: $Exports<'dependency-diff'>;
}
declare module 'dependency-diff/index.js' {
  declare module.exports: $Exports<'dependency-diff'>;
}
declare module 'dependency-diff/tests/diff/diff.js' {
  declare module.exports: $Exports<'dependency-diff/tests/diff/diff'>;
}
