// flow-typed signature: cb45efca2a553484e819060935bdaf8b
// flow-typed version: <<STUB>>/github-url-from-git_v^1.5.0/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'github-url-from-git'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'github-url-from-git' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'github-url-from-git/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'github-url-from-git/index' {
  declare module.exports: $Exports<'github-url-from-git'>;
}
declare module 'github-url-from-git/index.js' {
  declare module.exports: $Exports<'github-url-from-git'>;
}
declare module 'github-url-from-git/test.js' {
  declare module.exports: $Exports<'github-url-from-git/test'>;
}
