// flow-typed signature: 4901c692eafb4ad5d65e388b143570d6
// flow-typed version: <<STUB>>/update-nodejs-notifier_v^1.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'update-nodejs-notifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'update-nodejs-notifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'update-nodejs-notifier/lib/alerts' {
  declare module.exports: any;
}

declare module 'update-nodejs-notifier/lib/bake' {
  declare module.exports: any;
}

declare module 'update-nodejs-notifier/lib/versions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'update-nodejs-notifier/index' {
  declare module.exports: $Exports<'update-nodejs-notifier'>;
}
declare module 'update-nodejs-notifier/index.js' {
  declare module.exports: $Exports<'update-nodejs-notifier'>;
}
declare module 'update-nodejs-notifier/lib/alerts.js' {
  declare module.exports: $Exports<'update-nodejs-notifier/lib/alerts'>;
}
declare module 'update-nodejs-notifier/lib/bake.js' {
  declare module.exports: $Exports<'update-nodejs-notifier/lib/bake'>;
}
declare module 'update-nodejs-notifier/lib/versions.js' {
  declare module.exports: $Exports<'update-nodejs-notifier/lib/versions'>;
}
